<?php
/**
 * Copyright © Fisheye Media Ltd. All rights reserved.
 * See LICENCE.txt for licence details.
 */

use Magento\Framework\App\Action\Action;

/**
* Product list template
*
* @var $block \Alice\LandingPages\Block\MyProduct
* @var \Magento\Framework\Escaper $escaper
*/
$myProduct = $block->getProduct(1);
?>
<a href="<?= $escaper->escapeUrl($myProduct->getProductUrl()) ?>">
    <p><?= $escaper->escapeHtml(__('SKU: %1', $myProduct->getSku())) ?></p>
    <p><?= $escaper->escapeHtml(__('Name: %1', $myProduct->getName())) ?></p>
    <p><?= $escaper->escapeHtml(__('Price: ')); ?>
        <?= $block->formatPrice($myProduct->getFinalPrice()) ?></p>
    <img src="<?= $block->getProductImageUrl($myProduct, 'product_page_image_small') ?>"
         alt="<?= $escaper->escapeHtml(__('Product Image')) ?>"
         width="200"
         height="200"
    />
</a>
